name: AoC 2020 - Haskell

on:
  pull_request:
  push:
    branches:
    - trunk

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.3' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'

    - name: Test
      run: stack test

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: haskell-aoc-2020
        SLACK_MESSAGE: 'Test success'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
