name: AoC 2020 - Haskell

on:
  pull_request:
  push:
    branches:
    - trunk

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.8.3' # Exact version of ghc to use
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v2
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work

    - name: Build
      run: stack clean && stack build --no-run-tests

  test-day00:
    needs: test-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.8.3' # Exact version of ghc to use
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v2
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
        
    - name: Test
      run: stack build --test haskell-aoc:haskell-aoc-test-day00


  test-day01:
    needs: test-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.8.3' # Exact version of ghc to use
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v2
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
        
    - name: Test
      run: stack build --test haskell-aoc:haskell-aoc-test-day01

  test-done:
    needs: test-day01
    runs-on: ubuntu-latest

    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: haskell-aoc-2020
        SLACK_MESSAGE: 'Test success'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
